<a href="https://colab.research.google.com/github/Vhyvean/alx-pre_course/blob/master/NumPy_Array_Excercise2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Define arrays

# 1D Array
one_d = np.array([10, 11, 12, 13, 14])
print("1D Array:", one_d)

# 2D Array
two_d = np.array([[20, 30, 40, 50, 60],
                  [43, 54, 65, 76, 87],
                  [11, 22, 33, 44, 55]])
print("\n2D Array:\n", two_d)

# 3D Array
three_d = np.array([[[1, 2, 3, 4, 5],
                  [11, 21, 31, 41, 51]],
                 [[11, 12, 13, 14, 15],
                  [51, 52, 53, 54, 5]]])
print("\n3D Array:\n", three_d)

# 1. Slice the first column of the 2D array
first_col = two_d[:, 0]
print("\nFirst column of the 2D array:", first_col)

# 2. Slice the last two coloumns of the 2nd row of the 2D array
last_two_cols = two_d[1, -2:]
print("Last two columns of 2nd row:", last_two_cols)

# 3. Slice the 2nd row of the 2D array excluding the last two columns
exclude_last_two = two_d[1, :-2]
print("2nd row excluding last two columns:", exclude_last_two)






1D Array: [10 11 12 13 14]

2D Array:
 [[20 30 40 50 60]
 [43 54 65 76 87]
 [11 22 33 44 55]]

3D Array:
 [[[ 1  2  3  4  5]
  [11 21 31 41 51]]

 [[11 12 13 14 15]
  [51 52 53 54  5]]]

First column of the 2D array: [20 43 11]
Last two columns of 2nd row: [76 87]
2nd row excluding last two columns: [43 54 65]
