<a href="https://colab.research.google.com/github/Vhyvean/alx-pre_course/blob/master/NumPy_Array_Exercise3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# First set: 1D arrays of 10
# 1. "Empty" array (uninitialized values)
arr1 = np.empty(10, dtype=int)

# 2. Full of zeros (Using multiplication)
arr2 = np.arange(10) * 0

# 3. Full of 1s (Using boolean to int)
arr3 = (np.arange(10) >= 0).astype(int)

# 4. Full of 2s (Repeat a value)
arr4 = np.repeat(2, 10)

print("1D Arrays:")
print("Empty:", arr1)
print("Zeros:", arr2)
print("Ones:", arr3)
print("Twos:", arr4)


# Second set: 2D arrays (2x4)
# 1. Empty 2x4
arr5 = np.empty((2, 4), dtype=int)

# 2. Full of 0s (tile trick)
arr6 = np.tile(0, (2,4))

# 3. Full of 1s (Using boolean again)
arr7 = (np.arange(8).reshape(2,4) >= 0).astype(int)

# 4. Full of 2s (Using full_like with constant array)
arr8 = np.full_like(np.ones((2,4)), 2)

print("\n2D Arrays:")
print("Empty 2x4:\n", arr5)
print("Zeros 2x4:\n", arr6)
print("Ones 2x4:\n", arr7)
print("Twos 2x4:\n", arr8)
















1D Arrays:
Empty: [          682016328                   0                   0
                   0     132078834286592 3690752917652058164
 7220445817653900077 3258415234736284723 7305454541978285154
     284185929606195]
Zeros: [0 0 0 0 0 0 0 0 0 0]
Ones: [1 1 1 1 1 1 1 1 1 1]
Twos: [2 2 2 2 2 2 2 2 2 2]

2D Arrays:
Empty 2x4:
 [[679721405         0         0         0]
 [        0         0         0         0]]
Zeros 2x4:
 [[0 0 0 0]
 [0 0 0 0]]
Ones 2x4:
 [[1 1 1 1]
 [1 1 1 1]]
Twos 2x4:
 [[2. 2. 2. 2.]
 [2. 2. 2. 2.]]
